### ISSUE TITLE
Checkboxes aren't checked 

### ISSUE THREAD

**Issue by Utugnulla** [SillyCoon/grumma#59]

**Comment by SillyCoon** [comment]
@Utugnulla could you please provide screenshot/recording and the page where checkboxes don't work?

**Comment by Utugnulla** [comment]
https://github.com/user-attachments/assets/9810cd59-8f2e-40c6-98ea-0c20fe727cad



> @Utugnulla could you please provide screenshot/recording and the page where checkboxes don't work?
